<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
<meta charset="UTF-8" />
<title>PHPWord</title>
<meta name="author" content="Duong Anh Van" />
<style>
* {font-family: Arial; font-size: 11pt;}
a.NoteRef {text-decoration: none;}
hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
table {border: 1px solid black; border-spacing: 0px; width : 100%;}
td {border: 1px solid black;}
.Normal {margin-bottom: 8pt;}
h1 {font-family: 'Arial'; font-size: 16pt; font-weight: bold;}
h3 {font-family: '.VnTimeH'; font-size: 14pt; font-weight: bold;}
h4 {font-family: '.VnTimeH'; font-size: 11pt; font-weight: bold;}
.Heading 1 Char {font-family: 'Arial'; font-size: 16pt; font-weight: bold;}
.Heading 3 Char {font-family: '.VnTimeH'; font-size: 14pt; font-weight: bold;}
.Heading 4 Char {font-family: '.VnTimeH'; font-weight: bold;}
.Normal (Web) {font-size: 12pt;}
.Body Text {margin-bottom: 6pt;}
.Body Text Char {font-family: 'Times New Roman'; font-size: 10pt;}
.Table Paragraph {font-size: 11pt;}
</style>
<style>
                                     body {
                                       background-color: #ffffff;
                                     }
                                    </style></head>
<body>
<p style="text-align: right; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt; font-weight: bold; font-style: italic;">Phụ lục số 1:</span></p>
<table style="table-layout: fixed;">
<tr>
<td>
<h4>BỘ CÔNG THƯƠNG</h4>
<p style="text-align: center; margin-bottom: 0pt;"><span style="font-size: 13pt; font-weight: bold;">TRƯỜNG ĐẠI HỌC</span></p>
<p style="text-align: center; margin-bottom: 0pt;"><span style="font-size: 13pt; font-weight: bold;"> KINH TẾ -</span><span style="font-size: 13pt; font-weight: bold;"></span><span style="font-size: 13pt; font-weight: bold;"> </span><span style="font-size: 13pt; font-weight: bold;">KỸ THUẬT CÔNG NGHIỆP</span></p>
</td>
<td>
<h3>CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM</h3>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt; font-weight: bold;">Độc lập - Tự do - Hạnh phúc</span></p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt;"></span><span style="font-size: 13pt;"> </span></p>
</td>
</tr>
</table>
<h1></h1>
<h1>PHIẾU ĐÁNH GIÁ KẾT QUẢ RÈN LUYỆN</h1>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-style: italic;">(Kèm theo QĐ số: 644</span><span style="font-size: 12pt; font-style: italic;">/QĐ-ĐHKTKTCN ngày</span><span style="font-size: 12pt; font-style: italic;"> 01 </span><span style="font-size: 12pt; font-style: italic;">tháng 1</span><span style="font-size: 12pt; font-style: italic;">2</span><span style="font-size: 12pt; font-style: italic;"> năm 2020 của Hiệu trưởng</span></p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 12pt; font-style: italic;">Trường Đại học Kinh tế - Kỹ thuật Công nghiệp)</span></p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt; font-style: italic;">Học kỳ:</span><span style="font-size: 13pt; font-style: italic;"> </span><span style="font-size: 13pt; font-style: italic;">………</span>	<span style="font-size: 13pt; font-style: italic;">Năm học: 20</span><span style="font-size: 13pt; font-style: italic;">…. – 20……</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt;">Họ và tên sinh viên:</span>			<span style="font-size: 13pt;">Ngày sinh:</span><span style="font-size: 13pt;"> </span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt;">Mã SV:</span><span style="font-size: 13pt;"> </span><span style="font-size: 13pt;">………</span>		<span style="font-size: 13pt;">Lớp:</span><span style="font-size: 13pt;"> </span><span style="font-size: 13pt;"> </span><span style="font-size: 13pt;">DHTI14A2CL</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 13pt;">Khoa:</span><span style="font-size: 13pt;"> </span><span style="font-size: 13pt;">……</span><span style="font-size: 13pt;">CNTT</span><span style="font-size: 13pt;">…………</span>	<span style="font-size: 13pt;"> Cơ sở:</span><span style="font-size: 13pt;">..</span><span style="font-size: 13pt;">…</span><span style="font-size: 13pt;">Lĩnh Nam</span><span style="font-size: 13pt;">……...</span></p>
<p>&nbsp;</p>
<table style="table-layout: fixed;">
<tr>
<td rowspan="2">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">TT</span></p>
<p>&nbsp;</p>
</td>
<td rowspan="2">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Nội dung đáng giá</span></p>
<p>&nbsp;</p>
</td>
<td rowspan="2">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Điểm</span></p>
<p>&nbsp;</p>
</td>
<td colspan="2">
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Điểm đánh giá của</span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">SV</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Lớp</span></p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">A</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Điểm rèn luyện mặc định của sinh viên trong học kỳ</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">70</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">70</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">B</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Điểm rèn luyện được cộng trong kỳ </span><span style="font-size: 11pt; font-style: italic;">(điểm cộng/lần, hoạt động,…)</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">I</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm cộng về ý thức tham gia học tập</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Đạt kết quả học tập từ 7,0 trở lên </span><span style="font-size: 11pt; font-style: italic;">(theo thang điểm 10):</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Đạt điểm trung bình học tập trên 9,0</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Đạt điểm trung bình học tập từ 8,0 đến  9,0</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">3</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Đạt điểm trung bình học tập từ 7,0 đến  8,0</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có tinh thần cố gắng vượt khó, vươn lên trong học tập</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia các CLB học thuật, hoạt động NCKH, các cuộc thi khởi nghiệp sáng </span><span style="font-size: 11pt;">tạo; thi học sinh giỏi;… do Nhà</span><span style="font-size: 11pt;"> trường tổ chức hoặc được cử tham gia</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">4</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có thành tích khác:…………………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">II</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm cộng về ý thức chấp hành nội quy, quy chế, quy định trong</span><span style="font-size: 11pt; font-weight: bold; font-style: italic;"> nhà</span><span style="font-size: 11pt; font-weight: bold; font-style: italic;"> trường</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có các hành động tích cực trên các trang mạng xã hội phù hợp với chủ trương của Nhà trường, Nhà nước được tập thể ghi nhận</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">6</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia tích cực các hoạt động lao động công ích, giữ gìn an ninh trật tự góp phần xây dựng cho sự phát triển của Nhà trường</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">7</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia thực tập tăng cường năng lực nghề nghiệp tại các doanh nghiệp; các buổi hội thảo, khóa đào tạo kỹ năng mềm về hướng nghiệp, tư vấn giới thiệu việc làm,..</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">8</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia hoạt động khác:…………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">III</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm cộng về ý thức tham gia các hoạt động chính trị, xã hội, văn hóa, văn nghệ, thể thao, phòng chống tội phạm và các tệ nạn xã hội</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">9</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Được tham dự lớp học nhận thức về Đảng, được kết nạp Đảng, là Đảng viên hoàn thành tốt nhiệm vụ, Đoàn viên, Hội viên ưu tú,…</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">10</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia tích cực các hoạt động chính trị, xã hội, văn hóa, văn nghệ, thể thao của Nhà trường, khoa, lớp phát động và tổ chức</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">11</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia các hoạt động tình nguyện</span><span style="font-size: 11pt;">, hiến máu nhân đạo, công tác xã hội; tham gia tuyên truyền, phòng chống tội phạm và các tệ nạn xã hội</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">12</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia hoạt động trong các CLB do Đoàn thanh niên, Hội sinh viên tổ chức</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">13</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tham gia hoạt động khác:…………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">IV</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm cộng về ý thức công dân trong quan hệ cộng đồng</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">4</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tích cực tham gia tuyên truyền các chủ trương, đường lối, chính sách của Đảng và pháp luật của Nhà nước</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Tích cực tham gia các hoạt động giữ gìn an ninh trật tự, an toàn xã hội, các hoạt động tìm hiểu pháp luật</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">16</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có thành tích khác:…………………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">V</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0pt; margin-bottom: 0pt;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm cộng về ý thức và kết quả khi tham gia công tác cán bộ lớp, các đoàn thể, tổ chức trong Nhà trường hoặc sinh viên đạt được thành tích đặc biệt trong học tập, rèn luyện</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">7</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Lớp trưởng, Bí thư chi đoàn, Chi hội trưởng HSV, Chủ nhiệm các câu lạc bộ, tổ đội trong Nhà trường hoàn thành nhiệm vụ</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">8</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Lớp phó, Phó bí thư chi đoàn, Chi hội phó HSV, Phó chủ nhiệm các câu lạc bộ, tổ đội trong Nhà trường hoàn thành nhiệm vụ</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">9</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Tổ trưởng, cán sự bộ môn, ủy viên BCH chi đoàn hoàn thành nhiệm vụ</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">20</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;">Được khen thưởng hoặc đạt giải trong học tập và các hoạt động phong trào</p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">21</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có thành tích khác:…………………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">C</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold;">Điểm rèn luyện bị trừ trong kỳ </span><span style="font-size: 11pt; font-style: italic;">(điểm trừ/lần vi phạm, buổi,…)</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">I</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm trừ về ý thức học tập</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm quy chế thi, kiểm tra</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">4</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Thi lại môn học, học phần</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm thời gian học tập, thiếu ý thức trong học tập</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Nghỉ học không có lý do</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Đi học muộn, trốn tiết, bỏ giờ,..</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">1</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">4</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm khác:……………………………………………..………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">II</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm trừ về ý thức chấp hành </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">nội quy, quy chế, quy định trong</span><span style="font-size: 11pt; font-weight: bold; font-style: italic;"> nhà</span><span style="font-size: 11pt; font-weight: bold; font-style: italic;"> trường</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Đi học hộ hoặc nhờ người khác đi học hộ</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">6</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Không đóng học phí đúng thời hạn</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">7</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Không khai báo, chấp hành các quy định về nội, ngoại trú; Không nộp bài thu hoạch, bản cam kết,…theo quy định</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">8</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Không tham gia BHYT theo quy định</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">9</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm các nội quy, quy định của Nhà trường:</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Sử</span><span style="font-size: 11pt; font-style: italic;"> dụng trang phục không phù hợp </span><span style="font-size: 11pt; font-style: italic;">khi đến trường, trong lớp học</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Hút thuốc lá, ăn quà trong lớp, trong giờ học</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Sử dụng điện thoại, thiết bị nghe nhìn,… trong giờ học</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Không đeo thẻ sinh viên khi đến trường, trong lớp học</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">-</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">Không có ý thức giữ gìn vệ sinh lớp học, bỏ rác không đúng nơi quy định</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">10</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm khác:………………………………………..……………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">III</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm trừ về ý thức và kết quả tham gia các hoạt động chính trị, xã hội, văn hóa, văn nghệ, thể thao, phòng chống các tệ nạn xã hội</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">11</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm các quy định về an toàn giao thông, tệ nạn xã hội, các quy định về đời sống văn hóa, các trò chơi có nội dung không lành mạnh,…</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Không tham gia học tập “Tuần sinh hoạt công dân HSSV” đầu năm học</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">3</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">13</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm khác:………………..……………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">IV</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm trừ về ý thức công dân trong quan hệ với cộng cộng đồng</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">4</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm chủ trương, đường lối, chính sách của Đảng, pháp luật của Nhà nước</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Có hành vi gây mất đoàn kết, mất an ninh trật tự, an toàn xã hội trong trường, lớp và nơi cư trú</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">16</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm khác:……………………………..………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">V</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Điểm trừ về ý thức và kết quả tham gia công tác cán bộ lớp, các đoàn thể, tổ chức trong nhà trường</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">7</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Báo cáo không trung thực, có hành vi bao che cho vi phạm của sinh viên trong lớp</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">5</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">8</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Cán bộ lớp, cán bộ Đoàn, cán bộ Hội sinh viên chưa hoàn thành nhiệm vụ</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">1</span><span style="font-size: 11pt;">9</span></p>
</td>
<td>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">Vi phạm khác:………………………………………………………………………</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt;">2</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">D</span></p>
</td>
<td>
<p style="margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Tổng điểm rèn luyện của sinh viên trong học kỳ: D = A + B - C</span></p>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">(Nếu tổng điểm sinh viên đạt được &gt; 100 điểm thì quy về mức 100)</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">100</span></p>
</td>
<td>
<p>&nbsp;</p>
</td>
<td>
<p>&nbsp;</p>
</td>
</tr>
</table>
<p style="text-align: right; margin-top: 5.4pt;"><span style="font-style: italic;">Hà Nội, ngày 27</span><span style="font-style: italic;"> tháng</span><span style="font-style: italic;"> 12 năm 2021</span></p>
<table style="table-layout: auto;">
<tr>
<td>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-weight: bold;">Cố </span><span style="font-weight: bold;">vấn</span><span style="font-weight: bold;"> </span><span style="font-weight: bold;">học</span><span style="font-weight: bold;"> </span><span style="font-weight: bold;">tập</span></p>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-size: 11pt; font-style: italic;">(Ký, ghi </span><span style="font-size: 11pt; font-style: italic;">rõ</span><span style="font-size: 11pt; font-style: italic;"> </span><span style="font-size: 11pt; font-style: italic;">họ</span><span style="font-size: 11pt; font-style: italic;"> </span><span style="font-size: 11pt; font-style: italic;">tên)</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</td>
<td>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-weight: bold;">Lớp</span><span style="font-weight: bold;"> </span><span style="font-weight: bold;">trưởng</span></p>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-size: 11pt; font-style: italic;">(Ký, ghi </span><span style="font-size: 11pt; font-style: italic;">rõ</span><span style="font-size: 11pt; font-style: italic;"> </span><span style="font-size: 11pt; font-style: italic;">họ</span><span style="font-size: 11pt; font-style: italic;"> </span><span style="font-size: 11pt; font-style: italic;">tên)</span></p>
</td>
<td>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-weight: bold;">Sinh viên</span></p>
<p style="text-align: center; margin-top: 5.4pt;"><span style="font-size: 11pt; font-style: italic;">(Ký, ghi rõ họ tên)</span></p>
<p>&nbsp;</p>
</td>
</tr>
</table>
<p>&nbsp;</p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Lưu ý</span><span style="font-size: 11pt; font-style: italic;">: </span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên có kết quả học tập loại </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Xuất sắc</span><span style="font-size: 11pt; font-style: italic;">, </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Giỏi</span><span style="font-size: 11pt; font-style: italic;"> không có các vi phạm trong học kỳ; Sinh viên tiêu biểu có nhiều thành tích đóng góp cho các phong trào và sự phát triển của Nhà trường, được các đơn vị trong và ngoài trường xác nhận và đề nghị: Được xét điểm rèn luyện loại </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Xuất sắc</span><span style="font-size: 11pt; font-style: italic;">, </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Tốt</span><span style="font-size: 11pt; font-style: italic;"> tương ứng kết quả học tập hoặc thành tích được ghi nhận;</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên bị kỷ luật mức khiển trách tron</span><span style="font-size: 11pt; font-style: italic;">i</span><span style="font-size: 11pt; font-style: italic;">g học kỳ: Xếp điểm rèn luyện không quá loại </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Khá</span><span style="font-size: 11pt; font-style: italic;">;</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên bị kỷ luật mức cảnh cáo trong học kỳ: Xếp điểm rèn luyện không quá loại </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Trung bình</span><span style="font-size: 11pt; font-style: italic;">;</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên nộp phiếu đánh giá rèn luyện nhưng không tham gia họp xét</span><span style="font-size: 11pt; font-style: italic;"> nếu không có lý do chính đáng</span><span style="font-size: 11pt; font-style: italic;"> sẽ bị </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">hạ một bậc</span><span style="font-size: 11pt; font-style: italic;"> đánh giá điểm rèn luyện;</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên không nộp Phiếu đánh giá điểm rèn luyện: Xếp loại </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Kém</span><span style="font-size: 11pt; font-style: italic;">;</span></p>
<p style="text-align: justify; margin-top: 0; margin-bottom: 0;"><span style="font-size: 11pt; font-style: italic;">- Sinh viên đang trong quá trình bị đình chỉ học tập: </span><span style="font-size: 11pt; font-weight: bold; font-style: italic;">Không đánh giá.</span></p>
<p>&nbsp;</p>
<p>&nbsp;</p>
</body>
</html>
